### ISSUE TITLE
导入microservice-provider-user工程后显示The type org.springframework.data.repository.query.QueryByExampleExecutor cannot be resolved错误

### ISSUE THREAD

**Issue by 39627020** [eacdy/spring-cloud-book#5]
所用工具：STS 3.9
导入microservice-provider-user工程后显示The type org.springframework.data.repository.query.QueryByExampleExecutor cannot be resolved错误，请问如何解决呢？

**Comment by 39627020** [comment]
我将spring-boot-starter-parent修改为1.4.2.RELEASE后，可以编译，但是运行后报下面的错误。
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'entityManagerFactory' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:680) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1183) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:275) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	... 40 common frames omitted

**Comment by eacdy** [comment]
您好，建议执行`mvn clean install -U` 确保项目能够正常构建之后再启动。
